apiVersion: apps/v1
kind: Deployment
metadata:
  name: endpoint
spec:
  replicas: 1
  selector:
    matchLabels:
      app: endpoint
  template:
    metadata:
      labels:
        app: endpoint
    spec:
      containers:
        - name: endpoint
          image: localhost:5000/endpoint:latest
          ports:
            - containerPort: 50051
---
apiVersion: v1
kind: Service
metadata:
  name: endpoint
spec:
  selector:
    app: endpoint
  ports:
    - name: http
      protocol: TCP
      port: 50051
      targetPort: 50051
  type: ClusterIP
