apiVersion: v1
kind: PersistentVolume
metadata:
  name: ipfs-storage-pv-1
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  hostPath:
    path: "/mnt/data/ipfs-storage-pv-1"

