apiVersion: v1
kind: ConfigMap
metadata:
    name: vue-nginx-config
data:
    nginx.conf: |
        server {
            listen 80;
            server_name _;

            location / {
                root /usr/share/nginx/html;
                index index.html;
                try_files $uri /index.html;
            }

            location /admin/ {
                proxy_pass http://admin-service.default.svc.cluster.local:8000;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }

            error_page 404 /index.html;
        }
